theme: jekyll-theme-architect
title: Portfolio
description: Billy Leung

# Your name to show in the footer
author: Billy Leung

# --- List of links in the navigation bar --- #
navbar-links:
 About Me: "aboutme"
 CV Portfolio: "portfolio"
 
 # --- Footer social media links --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "bleung.uts@gmail.com"
  github: bleunguts
  
# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "bleunguts.github.io"

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - portfolio.md  
      
